version: '3'
services:
  flask-api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=hassanDB

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=hassanDB
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  

volumes:
  db_data:
